param(
    [string]$ApiHostName = "127.0.0.1",
    [int[]]$CandidatePorts = @(8000,8001,8002,8003,8004,8005,8006,8007,8008,8009,8010),
    [string]$HealthPath = "/health"
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$frontendEnvLocal = Join-Path $repoRoot "frontend/.env.local"

function Test-HealthEndpoint {
    param(
        [string]$Url
    )
    try {
        $response = Invoke-WebRequest -Uri $Url -Method GET -TimeoutSec 2 -UseBasicParsing
        return $response.StatusCode -ge 200 -and $response.StatusCode -lt 500
    }
    catch {
        return $false
    }
}

$resolvedPort = $null
foreach ($port in $CandidatePorts) {
    $healthUrl = "http://{0}:{1}{2}" -f $ApiHostName, $port, $HealthPath
    if (Test-HealthEndpoint -Url $healthUrl) {
        $resolvedPort = $port
        break
    }
}

if (-not $resolvedPort) {
    Write-Host ("[sync_frontend_env] 未探测到可用后端健康地址（{0}:{1}{2}）" -f $ApiHostName, ($CandidatePorts -join ','), $HealthPath) -ForegroundColor Yellow
    Write-Host "[sync_frontend_env] 将保留/写入默认 8000。" -ForegroundColor Yellow
    $resolvedPort = 8000
}

$target = "http://{0}:{1}" -f $ApiHostName, $resolvedPort

$content = @(
    "# Auto-generated by scripts/sync_frontend_env.ps1",
    "# Detected backend URL via health probe: $target",
    "VITE_DEV_API_TARGET=$target",
    "",
    "# Optional: uncomment to force runtime direct API base",
    "# VITE_API_BASE_URL=$target"
) -join "`r`n"

Set-Content -Path $frontendEnvLocal -Value $content -Encoding UTF8

Write-Host "[sync_frontend_env] 已写入 $frontendEnvLocal" -ForegroundColor Green
Write-Host "[sync_frontend_env] VITE_DEV_API_TARGET=$target" -ForegroundColor Green
Write-Host "[sync_frontend_env] 请重启前端 dev server 使变量生效。" -ForegroundColor Cyan
