"""initial migration

Revision ID: 92775bb6552e
Revises:
Create Date: 2026-02-27 21:49:07.090890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92775bb6552e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_dt_local', sa.String(), nullable=False),
    sa.Column('tz', sa.String(), nullable=False),
    sa.Column('birth_dt', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('solar_time_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('api_version_last', sa.String(), nullable=True),
    sa.Column('rule_version_last', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cases_updated_at', 'cases', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_user_time', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('birth_time_hour', sa.Integer(), nullable=True),
    sa.Column('birth_time_minute', sa.Integer(), nullable=True),
    sa.Column('birth_city', sa.String(), nullable=True),
    sa.Column('birth_longitude', sa.Float(), nullable=True),
    sa.Column('solar_time_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("gender IN ('M', 'F', 'U')", name='ck_member_gender'),
    sa.CheckConstraint('birth_time_hour IS NULL OR (birth_time_hour >= 0 AND birth_time_hour <= 23)', name='ck_member_birth_hour'),
    sa.CheckConstraint('birth_time_minute IS NULL OR (birth_time_minute >= 0 AND birth_time_minute <= 59)', name='ck_member_birth_minute'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_members_created', 'members', ['created_at'], unique=False)
    op.create_index('idx_members_owner', 'members', ['owner_id'], unique=False)
    op.create_index('idx_members_owner_created', 'members', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_members_owner_id'), 'members', ['owner_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_tokens_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('compute_flags', sa.JSON(), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('backend_json', sa.JSON(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('summary_level', sa.String(), nullable=True),
    sa.Column('summary_warning_count', sa.Integer(), nullable=True),
    sa.Column('summary_diff_count', sa.Integer(), nullable=True),
    sa.Column('summary_engine_primary', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_case_created', 'snapshots', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_snapshots_case_id'), 'snapshots', ['case_id'], unique=False)
    op.create_table('delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.String(), nullable=False),
    sa.Column('member_scope', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_scope'], ['members.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delegations_from_to', 'delegations', ['from_user_id', 'to_user_id'], unique=False)
    op.create_index(op.f('ix_delegations_from_user_id'), 'delegations', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_delegations_to_user_id'), 'delegations', ['to_user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('bazi_json', sa.String(), nullable=False),
    sa.Column('pillars_primary', sa.String(), nullable=True),
    sa.Column('ten_gods', sa.String(), nullable=True),
    sa.Column('five_elements', sa.String(), nullable=True),
    sa.Column('L_level', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('recommendation_engine', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('"L_level" >= 0 AND "L_level" <= 3', name='ck_event_l_level'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_event_confidence_score'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_member_created', 'events', ['member_id', 'created_at'], unique=False)
    op.create_index('idx_events_owner_created', 'events', ['owner_id', 'created_at'], unique=False)
    op.create_index('idx_events_owner_member', 'events', ['owner_id', 'member_id'], unique=False)
    op.create_index(op.f('ix_events_member_id'), 'events', ['member_id'], unique=False)
    op.create_index(op.f('ix_events_owner_id'), 'events', ['owner_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('base_member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('variations', sa.String(), nullable=True),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('results', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scenarios_created', 'scenarios', ['created_at'], unique=False)
    op.create_index('idx_scenarios_owner', 'scenarios', ['owner_id'], unique=False)
    op.create_index('idx_scenarios_owner_created', 'scenarios', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scenarios_owner_id'), 'scenarios', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_owner_id'), table_name='scenarios')
    op.drop_index('idx_scenarios_owner_created', table_name='scenarios')
    op.drop_index('idx_scenarios_owner', table_name='scenarios')
    op.drop_index('idx_scenarios_created', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_events_owner_id'), table_name='events')
    op.drop_index(op.f('ix_events_member_id'), table_name='events')
    op.drop_index('idx_events_owner_member', table_name='events')
    op.drop_index('idx_events_owner_created', table_name='events')
    op.drop_index('idx_events_member_created', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_delegations_to_user_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_from_user_id'), table_name='delegations')
    op.drop_index('idx_delegations_from_to', table_name='delegations')
    op.drop_table('delegations')
    op.drop_index(op.f('ix_snapshots_case_id'), table_name='snapshots')
    op.drop_index('idx_snapshots_case_created', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_members_owner_id'), table_name='members')
    op.drop_index('idx_members_owner_created', table_name='members')
    op.drop_index('idx_members_owner', table_name='members')
    op.drop_index('idx_members_created', table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_cases_updated_at', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
